name: mgc-test
services:
  test:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - ./.env.docker
    restart: unless-stopped